image: docker

stages:
  - build
  - test
  - deploy
  - cleanup

build_image:
  stage: build
  image: docker:git
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master

jshint:
  stage: test
  script:
    - apk add --no-cache nodejs bash
    - npm install -g jshint
    - bash -c "jshint server.js"
  allow_failure: true
